import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSideBar from "./components/LeftSideBar";
import RightSideBar from "./components/RightSideBar";
import PlayBar from "./components/PlayBar";
import FadeUp from "./Motions/FadingMotions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " h-screen bg-zinc-900  overflow-hidden flex "
        }
      >
        <LeftSideBar />
        {children}
        <RightSideBar />
        <PlayBar />
      </body>
    </html>
  );
}
